Repository NemesisRE/kiosk-mode, pull requests merged in 2023-11, with the labels that each got.

#131 Add block_context_menu option
  .hass/config/configuration.yaml
  .hass/config/inputs/booleans/kiosk-mode.yaml
  .hass/config/ui-lovelace-context-menu.yaml
  .hass/config/ui-lovelace.yaml
  README.md
  src/constants/index.ts
  src/kiosk-mode.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement

#132 Create kiosk-mode complements documentation
  KIOSK-MODE-COMPLEMENTS.md
  README.md
  images/kiosk-mode-complements/cards/climate-entities-card-elements.png
  images/kiosk-mode-complements/cards/more-info-button.png
Labels: 📝 documentation

#133 Add "how to move header to the bottom" to kiosk-mode complements
  KIOSK-MODE-COMPLEMENTS.md
Labels: 📝 documentation

#137 Update dependencies
  .github/workflows/build.yaml
  .github/workflows/hacs.yaml
  package.json
  yarn.lock
Labels: dependencies

#136 Add how to align tabs to the center to the kiosk-mode complements documentation
  KIOSK-MODE-COMPLEMENTS.md
Labels: 📝 documentation

#135 Improve the styles to move the header to the bottom in the kiosk-mode complements
  KIOSK-MODE-COMPLEMENTS.md
Labels: 📝 documentation

#134 Add how to hide the more-info dialogs header to the kiosk-mode complements
  KIOSK-MODE-COMPLEMENTS.md
Labels: 📝 documentation

#139 Remove inconsistencies from the README
  README.md
Labels: 📝 documentation

#140 Add Eslint config and fix all the Eslint issues
  .eslintrc.js
  package.json
  playwright.config.ts
  rollup.config.js
  src/conf-info.ts
  src/constants/index.ts
  src/kiosk-mode.ts
  src/styles/index.ts
  src/types/index.ts
  src/utilities/index.ts
  tests/constants/index.ts
  tests/main-options.spec.ts
  tests/more-info-dialogs.spec.ts
  tests/url-parameters.spec.ts
  tests/utils/index.ts
  yarn.lock
Labels: configuration
