Repository NemesisRE/kiosk-mode, pull requests merged in 2023-05, with the labels that each got.

#65 Update Home Assistant Docker image and remove config files from gitignore
  .gitignore
  package.json
Labels: configuration

#40 Update README.md
  AUTHORS
  README.md
Labels: documentation

#72 Change documentation to reflect the current behaviour with the sidebar open gesture
  README.md
Labels: documentation

#73 Change repository HACS badge by the default one
  README.md
Labels: documentation

#77 Make Kiosk Mode detects the Home Assistant version with development tags
  src/utilities/index.ts
Labels: feature
