Repository NemesisRE/kiosk-mode, pull requests merged in 2023-06, with the labels that each got.

#80 Get Lovelace config using a promise
  src/constants/index.ts
  src/kiosk-mode.ts
  src/utilities/index.ts
Labels: bug

#81 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#82 Change console.info styles
  src/conf-info.ts
Labels: bug

#83 Add auto_hide_overflow option
  .hass/config/inputs/booleans/kiosk-mode.yaml
  .hass/config/ui-lovelace.yaml
  README.md
  src/constants/index.ts
  src/kiosk-mode.ts
  src/types/index.ts
Labels: feature-request

#84 Update dependencies
  package.json
  rollup.config.js
  yarn.lock
Labels: dependencies

#85 Clean home assistant < 2023.4.x compatibility
  src/constants/index.ts
  src/kiosk-mode.ts
  src/styles/index.ts
  src/types/index.ts
  src/utilities/index.ts
Labels: refactoring

#87 Implement a block_overflow option and remove the auto_hide_overflow one
  .hass/config/configuration.yaml
  .hass/config/inputs/booleans/kiosk-mode.yaml
  .hass/config/ui-lovelace-overflow-mouse.yaml
  .hass/config/ui-lovelace.yaml
  README.md
  src/constants/index.ts
  src/kiosk-mode.ts
  src/styles/index.ts
  src/types/index.ts
Labels: feature

#89 Get all the main elements using promises
  .hass/config/.HA_VERSION
  package.json
  src/constants/index.ts
  src/kiosk-mode.ts
  src/utilities/index.ts
Labels: bug
